FROM php:8.2-cli
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip pdo pdo_mysql

RUN php -r "copy(https://getcomposer.org/installer, composer-setup.php);" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink(composer-setup.php);"

WORKDIR /app
COPY . /app

RUN composer install --no-interaction

ENTRYPOINT ["php", "artisan", "test"]
